/**
 * Source-observed Grok extension candidates. This is discovery input, not an
 * executable allowlist and not evidence that the installed binary implements
 * any route. Prefix-only rows are inventory groupings and are never dispatched.
 *
 * Source baseline: xai-org/grok-build 5163763 (package source declaring 1.0.4).
 */
export type GrokCandidateDirection =
  "client_to_agent" | "agent_to_client" | "unknown";

export type GrokCandidateKind = "request" | "notification" | "unknown";

export type GrokProbeDisposition =
  | "o2b_read_only"
  | "observe_only"
  | "deny_reverse_authority"
  | "inventory_only";

export interface GrokExtensionCandidate {
  readonly key: string;
  readonly literal?: string;
  readonly family: string;
  readonly direction: GrokCandidateDirection;
  readonly kind: GrokCandidateKind;
  readonly evidenceClass: "source_candidate";
  readonly probeDisposition: GrokProbeDisposition;
  readonly source: string;
}

const source =
  "protocol/grok-acp/1.0.4/source-route-candidates.json#current-source-evidence@5163763";

function candidate(
  key: string,
  family: string,
  direction: GrokCandidateDirection,
  kind: GrokCandidateKind,
  probeDisposition: GrokProbeDisposition,
  candidateSource = source,
): GrokExtensionCandidate {
  return Object.freeze({
    key,
    ...(key.endsWith("/*") ? {} : { literal: key }),
    family,
    direction,
    kind,
    evidenceClass: "source_candidate" as const,
    probeDisposition,
    source: candidateSource,
  });
}

/**
 * Append-preserving source-candidate ledger. Rows with a `/*` key deliberately
 * record a family whose complete route set or direction still requires exact
 * binary discovery. They must never be matched as prefixes at runtime.
 */
export const GROK_EXTENSION_CANDIDATES = Object.freeze([
  candidate(
    "x.ai/models/list",
    "models",
    "client_to_agent",
    "request",
    "o2b_read_only",
  ),
  candidate(
    "x.ai/models/update",
    "models",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/session/info",
    "session_lifecycle",
    "client_to_agent",
    "request",
    "o2b_read_only",
  ),
  candidate(
    "x.ai/session/list",
    "session_discovery",
    "client_to_agent",
    "request",
    "o2b_read_only",
  ),
  candidate(
    "x.ai/sessions/list",
    "session_discovery",
    "client_to_agent",
    "request",
    "o2b_read_only",
  ),
  candidate(
    "x.ai/workspaces/list",
    "workspace_discovery",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/updates",
    "session_replay",
    "client_to_agent",
    "request",
    "o2b_read_only",
  ),
  candidate(
    "x.ai/session/updates/chunk",
    "session_replay",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/session/state",
    "session_state",
    "client_to_agent",
    "request",
    "o2b_read_only",
  ),
  candidate(
    "x.ai/session/usage",
    "usage",
    "client_to_agent",
    "request",
    "o2b_read_only",
  ),
  candidate(
    "x.ai/commands/list",
    "commands",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/update",
    "session_updates",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/session_notification",
    "session_updates",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/sessions/changed",
    "session_discovery",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/session/prompt_complete",
    "prompt_completion",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/task_backgrounded",
    "task_activity",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/task_completed",
    "task_activity",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/follow_ups",
    "suggestions",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/announcements/update",
    "announcements",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/settings/update",
    "settings",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/queue/changed",
    "provider_queue",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/mcp/server_status",
    "mcp_activity",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/mcp/tools_changed",
    "mcp_activity",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/mcp/servers_updated",
    "mcp_activity",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "_x.ai/mcp/servers_updated",
    "leader_wrapped_mcp_activity",
    "agent_to_client",
    "notification",
    "inventory_only",
  ),
  candidate(
    "x.ai/log",
    "telemetry",
    "agent_to_client",
    "notification",
    "observe_only",
  ),
  candidate(
    "x.ai/ask_user_question",
    "structured_questions",
    "agent_to_client",
    "request",
    "deny_reverse_authority",
  ),
  candidate(
    "x.ai/exit_plan_mode",
    "plan_mode",
    "agent_to_client",
    "request",
    "deny_reverse_authority",
  ),
  candidate(
    "x.ai/folder_trust/request",
    "folder_trust",
    "agent_to_client",
    "request",
    "deny_reverse_authority",
  ),
  candidate(
    "x.ai/hooks/run",
    "hooks",
    "agent_to_client",
    "request",
    "deny_reverse_authority",
  ),
  candidate(
    "x.ai/mcp/sdk_call",
    "mcp_management",
    "agent_to_client",
    "request",
    "deny_reverse_authority",
  ),

  candidate(
    "x.ai/auth/*",
    "authentication",
    "unknown",
    "unknown",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/close",
    "session_lifecycle",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/import",
    "session_import",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/load_history",
    "session_replay",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/search",
    "session_search",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/resolve_local_for_worktree_resume",
    "session_repair",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/rehydrate",
    "session_repair",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/add_local_workspace",
    "workspace_mutation",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/rename",
    "rename",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/delete",
    "delete",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/update_mcp_servers",
    "mcp_management",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/fork",
    "fork",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session/repair",
    "session_repair",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/session_summaries/*",
    "session_discovery",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/compact_conversation",
    "compaction",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/recap",
    "recap",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate("x.ai/rewind/*", "rewind", "unknown", "unknown", "inventory_only"),
  candidate(
    "x.ai/interject",
    "provider_interject",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/queue/*",
    "provider_queue",
    "unknown",
    "unknown",
    "inventory_only",
  ),
  candidate(
    "x.ai/skills/*",
    "skills",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/workflows/list",
    "workflows",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/plugins/*",
    "plugins",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate("x.ai/hooks/*", "hooks", "unknown", "unknown", "inventory_only"),
  candidate(
    "x.ai/marketplace/*",
    "marketplace",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/mcp/*",
    "mcp_management",
    "unknown",
    "unknown",
    "inventory_only",
  ),
  candidate(
    "x.ai/task/*",
    "tasks",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/scheduler/*",
    "scheduler",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/subagent/*",
    "subagents",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/fs/*",
    "filesystem",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/terminal/*",
    "terminal",
    "unknown",
    "unknown",
    "inventory_only",
  ),
  candidate(
    "x.ai/git/*",
    "source_control",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/git/worktree/*",
    "worktrees",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate("x.ai/search/*", "search", "unknown", "unknown", "inventory_only"),
  candidate(
    "x.ai/code/*",
    "code_navigation",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/hunk-tracker/*",
    "hunk_tracking",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/review/*",
    "review",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/pr/*",
    "pull_requests",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/memory/*",
    "memory",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/cloud/*",
    "cloud",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/bundle/*",
    "bundle_sync",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/share_session",
    "sharing",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/billing",
    "billing",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/auto-topup-rule",
    "billing",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/privacy/setCodingDataRetention",
    "privacy",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/rollout/survey",
    "rollouts",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/feedback",
    "feedback",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/feedback/dismiss",
    "feedback",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/btw",
    "feedback",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/prompt_history",
    "prompt_history",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/suggest",
    "suggestions",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/suggestPrompt",
    "suggestions",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/internal/*",
    "internal_control",
    "unknown",
    "unknown",
    "inventory_only",
  ),
  candidate(
    "x.ai/debug/*",
    "debug",
    "client_to_agent",
    "request",
    "inventory_only",
  ),
  candidate(
    "x.ai/telemetry/*",
    "telemetry",
    "unknown",
    "unknown",
    "inventory_only",
  ),
  candidate(
    "x.ai/leader/*",
    "leader_relay",
    "unknown",
    "unknown",
    "inventory_only",
  ),
] as const satisfies readonly GrokExtensionCandidate[]);

export const GROK_REVIEWED_PROBE_CANDIDATES = Object.freeze(
  GROK_EXTENSION_CANDIDATES.filter(
    (entry) => entry.probeDisposition !== "inventory_only",
  ),
);

export function grokCandidateRouteKey(
  candidate: GrokExtensionCandidate,
): string {
  return `${candidate.direction}\u0000${candidate.kind}\u0000${candidate.literal ?? candidate.key}`;
}
