!ifndef SEDES_INSTALLER_INCLUDED
!define SEDES_INSTALLER_INCLUDED
!include LogicLib.nsh

# Keep the existing temp location and its permissions. Only change the Win32
# spelling: electron-builder's old uninstaller moves files into
# $PLUGINSDIR\old-install, which can exceed MAX_PATH even when $INSTDIR does not.
# This must reach the OLD executable through its environment, not just fix the
# uninstaller generated by this build. Do not bypass its process/file checks.
!macro sedesExtendedPath INPUT OUTPUT
  Push $R9
  StrCpy $R9 "${INPUT}" 4
  ${If} $R9 == "\\?\"
    StrCpy ${OUTPUT} "${INPUT}"
  ${Else}
    StrCpy $R9 "${INPUT}" 2
    ${If} $R9 == "\\"
      StrCpy ${OUTPUT} "${INPUT}" "" 2
      StrCpy ${OUTPUT} "\\?\UNC\${OUTPUT}"
    ${Else}
      StrCpy ${OUTPUT} "\\?\${INPUT}"
    ${EndIf}
  ${EndIf}
  Pop $R9
!macroend

!macro customInit
  Var /GLOBAL sedesOriginalTemp
  Var /GLOBAL sedesOriginalTmp
  Var /GLOBAL sedesUpgradeTemp
  ReadEnvStr $sedesOriginalTemp TEMP
  ReadEnvStr $sedesOriginalTmp TMP
  !insertmacro sedesExtendedPath $TEMP $sedesUpgradeTemp
  System::Call 'kernel32::SetEnvironmentVariable(t "TEMP", t "$sedesUpgradeTemp") i.r0'
  ${If} $0 == 0
    Abort "Unable to prepare long-path-safe upgrade temporary storage."
  ${EndIf}
  System::Call 'kernel32::SetEnvironmentVariable(t "TMP", t "$sedesUpgradeTemp") i.r0'
  ${If} $0 == 0
    Abort "Unable to prepare long-path-safe upgrade temporary storage."
  ${EndIf}
!macroend

!macro sedesRestoreEnvironment NAME VALUE
  ${If} ${VALUE} == ""
    System::Call 'kernel32::SetEnvironmentVariable(t "${NAME}", p 0)'
  ${Else}
    System::Call 'kernel32::SetEnvironmentVariable(t "${NAME}", t "${VALUE}")'
  ${EndIf}
!macroend

!macro sedesRefreshShortcut LINK
  # Rebuild retained shell-link metadata against the new executable. Keeping
  # the old .lnk bytes can leave Explorer unable to resolve the replaced target,
  # even though the displayed TargetPath still names the correct executable.
  # Never recreate an intentionally removed shortcut.
  ${If} ${FileExists} "${LINK}"
    ClearErrors
    CreateShortCut "${LINK}" "$appExe" "" "$appExe" 0 "" "" "${APP_DESCRIPTION}"
    ${If} ${Errors}
      MessageBox MB_OK|MB_ICONEXCLAMATION "Sedes was installed, but its shortcut could not be refreshed: ${LINK}" /SD IDOK
      Abort "Unable to refresh Sedes shortcut: ${LINK}"
    ${EndIf}
    WinShell::SetLnkAUMI "${LINK}" "${APP_ID}"
  ${EndIf}
!macroend

!macro customInstall
  # Restore before electron-builder launches Sedes. No registry/system/user
  # environment is changed; cancellation also discards this process's overrides.
  !insertmacro sedesRestoreEnvironment TEMP $sedesOriginalTemp
  !insertmacro sedesRestoreEnvironment TMP $sedesOriginalTmp
  ${If} $keepShortcuts == "true"
    !ifndef DO_NOT_CREATE_START_MENU_SHORTCUT
      !insertmacro sedesRefreshShortcut $newStartMenuLink
    !endif
    !ifndef DO_NOT_CREATE_DESKTOP_SHORTCUT
      ${IfNot} ${isNoDesktopShortcut}
        !insertmacro sedesRefreshShortcut $newDesktopLink
      ${EndIf}
    !endif
  ${EndIf}
  # Installation has completed. Launch the executable, not a retained .lnk
  # whose shell resolution/cache is independent of filesystem existence.
  StrCpy $launchLink "$appExe"
!macroend

!endif
