!ifndef SEDES_INSTALLER_INCLUDED
!define SEDES_INSTALLER_INCLUDED
!include LogicLib.nsh

# Keep the existing temp location and its permissions. Only change the Win32
# spelling: electron-builder's old uninstaller moves files into
# $PLUGINSDIR\old-install, which can exceed MAX_PATH even when $INSTDIR does not.
# This must reach the OLD executable through its environment, not just fix the
# uninstaller generated by this build. Do not bypass its process/file checks.
!macro sedesExtendedPath INPUT OUTPUT
  Push $R9
  StrCpy $R9 "${INPUT}" 4
  ${If} $R9 == "\\?\"
    StrCpy ${OUTPUT} "${INPUT}"
  ${Else}
    StrCpy $R9 "${INPUT}" 2
    ${If} $R9 == "\\"
      StrCpy ${OUTPUT} "${INPUT}" "" 2
      StrCpy ${OUTPUT} "\\?\UNC\${OUTPUT}"
    ${Else}
      StrCpy ${OUTPUT} "\\?\${INPUT}"
    ${EndIf}
  ${EndIf}
  Pop $R9
!macroend

!macro customInit
  Var /GLOBAL sedesOriginalTemp
  Var /GLOBAL sedesOriginalTmp
  Var /GLOBAL sedesUpgradeTemp
  ReadEnvStr $sedesOriginalTemp TEMP
  ReadEnvStr $sedesOriginalTmp TMP
  !insertmacro sedesExtendedPath $TEMP $sedesUpgradeTemp
  System::Call 'kernel32::SetEnvironmentVariable(t "TEMP", t "$sedesUpgradeTemp") i.r0'
  ${If} $0 == 0
    Abort "Unable to prepare long-path-safe upgrade temporary storage."
  ${EndIf}
  System::Call 'kernel32::SetEnvironmentVariable(t "TMP", t "$sedesUpgradeTemp") i.r0'
  ${If} $0 == 0
    Abort "Unable to prepare long-path-safe upgrade temporary storage."
  ${EndIf}
!macroend

!macro sedesRestoreEnvironment NAME VALUE
  ${If} ${VALUE} == ""
    System::Call 'kernel32::SetEnvironmentVariable(t "${NAME}", p 0)'
  ${Else}
    System::Call 'kernel32::SetEnvironmentVariable(t "${NAME}", t "${VALUE}")'
  ${EndIf}
!macroend

!macro customInstall
  # Restore before electron-builder launches Sedes. No registry/system/user
  # environment is changed; cancellation also discards this process's overrides.
  !insertmacro sedesRestoreEnvironment TEMP $sedesOriginalTemp
  !insertmacro sedesRestoreEnvironment TMP $sedesOriginalTmp
!macroend

!endif
