/** Runtime-neutral comparison bounds shared by protocol validation and Git engines. */
export const WORKSPACE_DIFF_MAX_REPOSITORIES = 32;
export const WORKSPACE_DIFF_DEFAULT_REF_PAGE_SIZE = 200;
export const WORKSPACE_DIFF_MAX_REFS = 1_000;
export const WORKSPACE_DIFF_DEFAULT_FILE_PAGE_SIZE = 250;
export const WORKSPACE_DIFF_MAX_FILE_PAGE_SIZE = 1_000;
export const WORKSPACE_DIFF_MAX_CHANGED_FILES = 10_000;
export const WORKSPACE_DIFF_MAX_PATCH_BYTES = 4 * 1_024 * 1_024;
export const WORKSPACE_DIFF_MAX_SIDE_BYTES = 16 * 1_024 * 1_024;
export const WORKSPACE_DIFF_MAX_REF_LABEL_BYTES = 1_024;
export const WORKSPACE_DIFF_MAX_REVIEW_SELECTION_BYTES = 64 * 1_024;
export const WORKSPACE_DIFF_MAX_REVIEW_SELECTION_LINES = 500;
export const WORKSPACE_DIFF_MAX_LIVE_COMPARISONS = 64;
export const WORKSPACE_DIFF_COMPARISON_IDLE_TTL_MS = 20 * 60 * 1_000;
export const WORKSPACE_DIFF_REVISION_IDLE_TTL_MS = 30 * 60 * 1_000;
export const WORKSPACE_DIFF_REPOSITORY_IDLE_TTL_MS = 60 * 60 * 1_000;
export const WORKSPACE_DIFF_MAX_LIVE_REVISIONS_PER_REPOSITORY =
  WORKSPACE_DIFF_MAX_REFS + WORKSPACE_DIFF_MAX_LIVE_COMPARISONS * 2;
export const WORKSPACE_DIFF_MAX_LIVE_REVISIONS = 4_096;
